markdown: kramdown
highlighter: rouge
pygments: true

enableRobotsTXT: true

# Site name (head)
name: ActivityPhp Core Documentation

# Site description (head)
description: A PHP implementation of ActivityPub core types protocol based upon the ActivityStreams 2.0 data format.

# Github repositories and download URLs
repository_url    : https://github.com/rtio/activitypub-core
doc_repository_url: https://github.com/rtio/activitypub-core/tree/master/docs
github_author_url : https://github.com/rtio
doc_baseurl       : https://rtio.github.io/activitypub-core
github_author_name: rtio

